### ISSUE TITLE
boolean fields starting with "is" are never filled

### ISSUE THREAD

**Issue by vincent-petit** [mtedone/podam#290]
boolean fields starting with "is" are never set by podam, using lombok for getter/setter.

How to reproduce:
```
// Using lombok, the method signature for getter and setter are:
// * isCondition1() / isCondition2() 
// * setCondition1(boolean condition) / setCondition2(boolean condition)
@lombok.Data
class ClassWithBoolean {
  boolean condition1;
  boolean isCondition2;
}
```

```
ClassWithBoolean expected = new ClassWithBoolean();
expected.setCondition1(true);
expected.setCondition2(true);
// The below assert failed, the field isCondition2 is always false
Assertions.assertThat(new PodamFactoryImpl().manufacturePojo(ClassWithBoolean.class))
      .isEqualTo(expected);
```

Versions:
Podam:7.2.6
Lombok:1.18.20  / https://projectlombok.org/features/GetterSetter

**Comment by daivanov** [comment]
Hi,

  Yes, this is because such naming violates is non-standard for Java Beans. 
   To make it work you should implement your own ClassInfoStrategy, which will be picking up non-standard properties. One way of doing this is to subclass AbstractClassInfoStrategy.
  Then just set this ClassInfoStrategy to the PodamFactory
  https://mtedone.github.io/podam/apidocs/uk/co/jemos/podam/api/PodamFactory.html#setClassStrategy-uk.co.jemos.podam.api.ClassInfoStrategy-

Thanks, Daniil
