### ISSUE TITLE
Exclude attributes without using annotations

### ISSUE THREAD

**Issue by mnd999** [mtedone/podam#80]
It would be nice to provide a mechanism where excluded attributes could be provided by the strategy without having to annotate them, perhaps by returning excluded attribute names.

**Comment by daivanov** [comment]
Could you please give an overview of the background. Why do you exclude attributes? They don't work, heavy to fill, maybe some other reason?

**Comment by mnd999** [comment]
On Thursday 26 Feb 2015 04:50:19 Daniil Ivanov wrote:
> Could you please give an overview of the background. Why do you exclude
> attributes? They don't work, heavy to fill, maybe some other reason?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mtedone/podam/issues/80#issuecomment-76172636

Sure, we're writing a Dao test that generates a random object graph using 
Podam, saves it, loads it back and makes sure it hasn't changed.

In the application logic, the object is mostly populated on one flow and then 
a later message on another flow populates one of the child objects on the 
graph. We'd like to be able to test the whole object graph with and without 
this child object generated to ensure the Dao still works in both cases.

**Comment by mtedone** [comment]
I think it might be the same concept as transient variables. It could be a
good idea

**Comment by daivanov** [comment]
So PODAM produces a object graph with all nodes filled (or not?).
Then instead of setting some child to null with something like this `pojo.getNode().getAnotherNode().getOtherNode.setChild(null)`, you want PODAM to produce object graph with `child` attribute filled and another time without it?

**Comment by mtedone** [comment]
That's not what I meant. Podam should behave as is by default but if there
was a way to instruct it not to fill only certain attributes on an
exception basis (I think we have an Attribute...data structure that maybe
we could leverage) it could be useful. But it should be users that would
need to set that data structure according to their needs. Podam by default
should fill in all attributes.

**Comment by daivanov** [comment]
As use-case was stated (maybe it's more complex in reality?) `setAttribute(null)` does the trick. Doing it through DataProviderStrategy will method `addExcludedAttibute(Class<?>, String attributeName);` cause the twice large code: two lines instead of one. Aditionally, one will be relying on very complicated solution (PODAM) instead of very simple and thus robust solution such as setter.

Also term object graph concerns me. Object graph typically means something like

    class Node {
        String attribute;
        List<Node> children;
    }

So if one tells PODAM to exclude attribute "attribute" all object graph's classes won't have it set. I don't think this is what is desired here.

**Comment by daivanov** [comment]
Fixed in PODAM 5.2.0.

**Comment by onacit** [comment]
So how can I do that? Is there any examples for this? @daivanov
